#!/usr/bin/busybox sh
# shellcheck shell=busybox disable=SC3003

set -eo pipefail

SCRIPT_NAME="zfs-prepare-rootfs"
LIB_DIR="/usr/lib/zfs/initcpio"
# shellcheck source=zfs-functions
. "$LIB_DIR/zfs-functions"


#
# main
#

setup_debug

if vars_present; then
	load_vars
else
	parse_cmdline
fi

case "${ZFS_ROOT_MODE?}" in
all)
	if dataset=$(zpool list -Ho bootfs | grep -m1 -vFx -); then
		ZFS_ROOT_POOL="${dataset%%/*}"
		ZFS_ROOT_DATASET="$dataset"
	else
		die "no pool with bootfs property found"
	fi
	;;

pool)
	[[ ${ZFS_ROOT_POOL+set} ]] || die "internal: \$ZFS_ROOT_POOL not set"

	if dataset=$(zpool list -Ho bootfs "$ZFS_ROOT_POOL" | grep -m1 -vFx -); then
		ZFS_ROOT_DATASET="$dataset"
	else
		die "no bootfs property found for pool \"$ZFS_ROOT_POOL\""
	fi
	;;

dataset)
	[[ ${ZFS_ROOT_POOL+set} ]] || die "internal: \$ZFS_ROOT_POOL not set"
	[[ ${ZFS_ROOT_DATASET+set} ]] || die "internal: \$ZFS_ROOT_DATASET not set"
	;;

*)
	die "invalid \$ZFS_ROOT_MODE=\"$ZFS_ROOT_MODE\""
	;;
esac

dump_vars

log "done"
exit 0

# vim: ft=sh ts=8 noet:
