#!/usr/bin/busybox sh
# shellcheck shell=busybox disable=SC3003

set -eo pipefail


#
# functions
#

# usage: log "message" [level]
if [[ -t 2 ]]; then
	log() {
		echo "zfs-prepare-rootfs: $1" >&2
	}
elif [[ -n $JOURNAL_STREAM ]] \
  && [[ -e /proc/self/fd/2 ]] \
  && [[ "$(stat -L -c "%d:%i" /proc/self/fd/2)" == "$JOURNAL_STREAM" ]]; then
	log() {
		echo "<${2:-"6"}>$1" >&2
	}
else
	log() {
		echo "<${2:-"6"}>zfs-prepare-rootfs: $1" >/dev/kmsg
	}
fi

die() {
	log "fatal: $1" "${2-"2"}"
	exit 1
}


#
# main
#

case "${ZFS_ROOT_MODE:?}" in
all)
	if dataset=$(zpool list -Ho bootfs | grep -m1 -vFx -); then
		:
	else
		die "no pool with bootfs property found"
	fi
	;;

pool)
	[[ ${ZFS_ROOT_POOL+set} ]] || die "internal: \$ZFS_ROOT_POOL not set"

	if dataset=$(zpool list -Ho bootfs "$ZFS_ROOT_POOL" | grep -m1 -vFx -); then
		:
	else
		die "no bootfs property found for pool \"$ZFS_ROOT_POOL\""
	fi
	;;

dataset)
	[[ ${ZFS_ROOT_DATASET+set} ]] || die "internal: \$ZFS_ROOT_DATASET not set"
	exit 0
	;;

*)
	die "invalid \$ZFS_ROOT_MODE=\"$ZFS_ROOT_MODE\""
	;;
esac

log "resolved: \$ZFS_ROOT_DATASET=$dataset"
exec systemctl set-environment ZFS_ROOT_DATASET="$dataset"

# vim: ft=sh ts=8 noet:
